### ISSUE TITLE
some problems

### ISSUE THREAD

**Issue by Moonkisscy** [craymichael/CNN_LCD#2]
I am a beginner . How to do solve this? I try to run this program.
1.ImportError: No module named overfeat
I install overfeat according to the official website.It shows that install ok.Is this difffrent to the official?
`tar xvf overfeat-vXX.tgz
./download_weights.py
sudo apt-get install build-essential gcc g++ gfortran git libgfortran3
cd /tmp
git clone https://github.com/xianyi/OpenBLAS.git
cd OpenBLAS
make NO_AFFINITY=1 USE_OPENMP=1
sudo make install
`
2.run the code "python setup.py install" 
UserWarning: Unknown distribution option: 'install_requires'
  warnings.warn(msg)
running install
running build
running build_ext
building 'overfeat' extension
gcc -pthread -fno-strict-aliasing -g -O2 -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -fPIC -I../../src -I/home/cy/anaconda3/envs/tensorflow27/lib/python2.7/site-packages/numpy/core/include -I/home/cy/anaconda3/envs/tensorflow27/include/python2.7 -c overfeatmodule.cpp -o build/temp.linux-x86_64-2.7/overfeatmodule.o -fopenmp
cc1plus: warning: command line option ‘-Wstrict-prototypes’ is valid for C/ObjC but not for C++ [enabled by default]
In file included from ../../src/THTensor.hpp:5:0,
                 from ../../src/overfeat.hpp:4,
                 from overfeatmodule.cpp:3:
../../src/TH/TH.h:4:23: fatal error: THGeneral.h: No such file or directory
 #include "THGeneral.h"
                       ^
compilation terminated.
error: command 'gcc' failed with exit status 1

**Comment by Moonkisscy** [comment]
(tensorflow36) cy@pc:~/loopclosure/CNN_LCD-master$ python cnn_lcd.py 
Python 3 detected: OverFeat unavailable.
2018-12-29 17:15:29.540218: F tensorflow/core/platform/cpu_feature_guard.cc:37] The TensorFlow library was compiled to use AVX instructions, but these aren't available on your machine.
Aborted (core dumped)

**Comment by Moonkisscy** [comment]
run'python setup.py install'

(tensorflow36) cy@pc:~/loopclosure/CNN_LCD-master/overfeat/API/python$ python setup.py install
/home/cy/anaconda3/envs/tensorflow36/lib/python3.6/distutils/dist.py:261: UserWarning: Unknown distribution option: 'install_requires'
  warnings.warn(msg)
running install
running build
running build_ext
building 'overfeat' extension
gcc -pthread -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -fPIC -I../../src -I/home/cy/.local/lib/python3.6/site-packages/numpy/core/include -I/home/cy/anaconda3/envs/tensorflow36/include/python3.6m -c overfeatmodule.cpp -o build/temp.linux-x86_64-3.6/overfeatmodule.o -fopenmp
cc1plus: warning: command line option ‘-Wstrict-prototypes’ is valid for C/ObjC but not for C++ [enabled by default]
In file included from ../../src/THTensor.hpp:5:0,
                 from ../../src/overfeat.hpp:4,
                 from overfeatmodule.cpp:3:
../../src/TH/TH.h:4:23: fatal error: THGeneral.h: No such file or directory
 #include "THGeneral.h"
                       ^
compilation terminated.
error: command 'gcc' failed with exit status 1

**Comment by Moonkisscy** [comment]
install OpenBLAS

make -j 2 -f Makefile.install install
make[1]: Entering directory `/tmp/OpenBLAS'
Generating openblas_config.h in /path/to/your/installation/include
Generating f77blas.h in /path/to/your/installation/include
Generating cblas.h in /path/to/your/installation/include
Copying LAPACKE header files to /path/to/your/installation/include
Copying the static library to /path/to/your/installation/lib
Copying the shared library to /path/to/your/installation/lib
Generating openblas.pc in /path/to/your/installation/lib/pkgconfig
Generating OpenBLASConfig.cmake in /path/to/your/installation/lib/cmake/openblas
Generating OpenBLASConfigVersion.cmake in /path/to/your/installation/lib/cmake/openblas
Install OK!

**Comment by Moonkisscy** [comment]
How to do solve it ,please help me .thanks.

**Comment by craymichael** [comment]
`Python 3 detected: OverFeat unavailable.`
You need to run the code with OverFeat installed using Python 2.7. If you are not trying to use OverFeat, you will need to clone the [TensorFlow slim models repo](https://github.com/tensorflow/models/tree/master/research/slim) locally.

`python setup.py install`
Ensure you are using Python 2.7 again. The last time I used OverFeat I was only able to run using Python 2.7 and I believe that is the only supported version of Python for the API. 

Let me know if this resolves your issues. Keep in mind the open [OverFeat issue](https://github.com/sermanet/OverFeat/issues/39).

**Comment by Moonkisscy** [comment]
> `Python 3 detected: OverFeat unavailable.`
> You need to run the code with OverFeat installed using Python 2.7. If you are not trying to use OverFeat, you will need to clone the [TensorFlow slim models repo](https://github.com/tensorflow/models/tree/master/research/slim) locally.
> 
> `python setup.py install`
> Ensure you are using Python 2.7 again. The last time I used OverFeat I was only able to run using Python 2.7 and I believe that is the only supported version of Python for the API.
> 
> Let me know if this resolves your issues. Keep in mind the open [OverFeat issue](https://github.com/sermanet/OverFeat/issues/39).

Thanks very much I run the code with OverFeat installed using Python 2.7. That remind me using Python 3. So I install Python 3.I also git clone the TensorFlow slim models repo locally.Do you mean I can run this program without overfeat?

**Comment by Moonkisscy** [comment]
Install overfeat  bug:
cy@pc:~/loopclosure/CNN_LCD-master/overfeat$ ./bin/linux_64/overfeat -n 3 samples/bee.jpg 
sh: 1: convert: not found
/home/cy/loopclosure/CNN_LCD-master/overfeat/bin/linux_64/overfeatcmd: error while loading shared libraries: libopenblas.so.0: cannot open shared object file: No such file or directory

**Comment by craymichael** [comment]
Yes you can run this without overfeat. Python 3 allows for use of TF slim models (inception, resnet, etc.), and Python 2 allows for use of overfeat. See [this answer](https://github.com/sermanet/OverFeat/issues/10#issuecomment-40912417) to resolve your issue.

**Comment by craymichael** [comment]
With Python 3.6, you seem to have a problem with the installed version of TensorFlow - apparently, the one installed with pip is pre-compiled with AVX instructions which your CPU does not support (see [this issue](https://github.com/tensorflow/tensorflow/issues/24548)). You should either [build TensorFlow from source](https://www.tensorflow.org/install/source) or retry installing from conda, see [this page](https://www.pugetsystems.com/labs/hpc/TensorFlow-Installation-CPU-version-1129/#using-anaconda-python-with-conda-my-recommendation). Additionally, I have seen posts that say downgrading TensorFlow (e.g. to 1.5) may fix this issue for Python 3.6. This is a conda-specific issue which apparently occurs only with Python 3 and not 2.7.

Regarding the OverFeat issue, you may need to ask sermanet how to proceed. Off-hand, it appears that "THGeneral.h" may be named incorrectly. Try renaming "src/TH/THGeneral.h.in" to "src/TH/THGeneral.h"

**Comment by Moonkisscy** [comment]
Also,for below three positional arguments, I don't know what to write in "WEIGHTS_DIR","WEIGHTS_BASE","LAYER " for python3. What are these three parameters used for?I'm sorry to ask you so many questions. Thank you very much for your reply these days
--weights_dir WEIGHTS_DIR
                        Weights directory.
  --weights_base WEIGHTS_BASE
                        Basename of weights file.
  --layer LAYER         Layer number to extract features from.

**Comment by craymichael** [comment]
You are most welcome, I'm glad things are finally working for you.

> Have you ever published a paper on CNN Loop Closure Detection?

I have not published specifically on loop-closure detection, but have recently had a paper accepted on autonomous driving.

> Do you think is it ok to improve on this repository? If I can improve it, What can be improved?

Definitely, the current method does not work very well. I would definitely give the original paper, "[Loop closure detection for visual SLAM systems using convolutional neural network](https://www.semanticscholar.org/paper/Loop-closure-detection-for-visual-SLAM-systems-Zhang-Su/8f9dce8bf9057172659cd54a9c509603344a3a2d)," a read and those that cite it, such as the papers listed [here](https://scholar.google.com/scholar?cites=12996852085246441310&as_sdt=8005&sciodt=0,7&hl=en). The similarity metric is quite simple (and unsupervised) and could definitely be improved.

Regarding the program arguments, here is some more information:
- LAYER: The name of the layer to extract features from. It should be sufficient to not touch this argument and just use the defaults.
- WEIGHTS_DIR: The directory in which you have downloaded the OverFeat weights (accurate and fast networks). By default this is "./OverFeat/data/default". You can download weights using the provided `./download_weights.py`  script in the [OverFeat repo](https://github.com/sermanet/OverFeat).
- WEIGHTS_BASE: The basename of the weights (starting name of the weights files in WEIGHTS_DIR, which if you did not rename, you don't need this argument).

I'm closing the issue for now as the original problem has been resolved, but feel free to continue commenting.
