### ISSUE TITLE
use my photo?

### ISSUE THREAD

**Issue by IConquer96** [craymichael/CNN_LCD#3]
Hello, can I judge the similarity by entering my own two photos?

**Comment by craymichael** [comment]
Hi, there is not a built-in way to do this currently, but if you could modify [this highlighted line in cnn_lcd.py](https://github.com/craymichael/CNN_LCD/blob/master/cnn_lcd.py#L379). For example, you could change it to something like the following:

```python
from scipy.ndimage import imread
...
# Load your images
imgs = np.asarray([imread(my_image) for my_image in my_image_dir])
# Spoof the ground truth (unless you have it)
n_imgs = len(imgs)
gt = np.full([n_imgs, n_imgs], 0.)
```

Let me know how things go!

**Comment by IConquer96** [comment]
i change the code like you said:

> # Load your images
    my_img_dir = 'ldata/'
    imgs = np.asarray([imread(my_img_dir+my_image) for my_image in os.listdir('ldata')])
    # Spoof the ground truth (unless you have it)
    n_imgs = len(imgs)
    gt = np.full([n_imgs, n_imgs], 0.)

and this (cause i don't have the ground truth):
> 

    # Compute similarity matrix
    sim = similarity_matrix(descs, gt, plot=True, cluster=True, median=False,
                            k_size=k_size, name='_'.join([args.dataset, model_name]))

but i think the result may be wrong ,i used two diffrent images and two similar images ,got the same images like that 
![Figure_1-1](https://user-images.githubusercontent.com/31886180/56781278-430c6b00-6815-11e9-947d-ccebd2b97cbc.png)
 but when i use 100+ images ,it shows that:
![Figure_1](https://user-images.githubusercontent.com/31886180/56781486-ed848e00-6815-11e9-87e7-9074698f9484.png)

**Comment by craymichael** [comment]
This may be an issue of image interpolation. It may also be a limitation of the method, which is unsupervised. I expect the method to perform poorly with a small amount of data, especially as the similarity values are normalized globally (i.e. by the largest difference between image descriptors).

Try removing interpolation from lines 244 and 258 of cnn_lcd.py:
```python
cax = ax.imshow(sim, cmap='coolwarm', interpolation='none',
                vmin=0., vmax=1.)
```

**Comment by IConquer96** [comment]
i did the change as you said,but nothing went good ,so i give up,but i have one more question?why i run the code as you wrote ,the average precision is so low,and the p-r cure is not like the ariticle?

**Comment by craymichael** [comment]
Performance will vary depending on the parameters used (e.g. for clustering or median filtering), and the CNN model. I could not replicate their results (from the article) exactly using the Overfeat model so tried methods of improving the detection quality.

**Comment by IConquer96** [comment]
okay,thank you!!
