### ISSUE TITLE
The result of running the  project named CNN_LCD in your github is not in  keeping with your published  paper. 

### ISSUE THREAD

**Issue by yuyuyuyuyu1234** [craymichael/CNN_LCD#5]
The result of running the  project named CNN_LCD in your github is not in  keeping with your published  paper. 

闭环检测的代码运行结果于论文不相符。

**Comment by craymichael** [comment]
Hi, please note that I am not an author of the paper, but have simply attempted to reproduce their results. No method I have tried has been able to obtain their exact performance, but the code I have serves as a framework to test their method.
