### ISSUE TITLE
The precision of loop closure is very low. How could I improve it?

### ISSUE THREAD

**Issue by xiaoxueshengyao** [craymichael/CNN_LCD#6]
When I used "Inceptin_v1" as the predict model, I can got the score confusion matrix, but Precision-Recall curve is not ideal, especially the precision is always under 0.2, what ever I used v2/v3/v4. 
That's what I run
`python3 cnn_lcd.py --dataset college inception_v1 `
and the result about precision_recall:
`Average Precision: 0.16354226114901457
Best MPC-ACC (thresh=0.38): 0.8863359002585536
Precision (thresh=0.38): 0.05770001215400474
Recall (thresh=0.38): 0.8642125134843581`
In other way, I think the sim confusion matrix is not suited the precision. 
How can I improve it.
I will be appreciate if you can reply me.

**Comment by craymichael** [comment]
Hi, please see #5 and some of the comments in #3 and #1 for details on improving performance. Basically, you can sweep parameters and the models, but the performance is not very satisfactory. Other methods should be explored to decide LCD classification, e.g. local thresholds of the distance map.
